// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYUqiHtxWdlc34S1fVOJcKVvcehnWQ9PU',
    appId: '1:1050523682496:web:3e765c651c0285733f0f25',
    messagingSenderId: '1050523682496',
    projectId: 'netplixclone',
    authDomain: 'netplixclone.firebaseapp.com',
    storageBucket: 'netplixclone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAKx6Mswwl4Z6ftJfr5TdiyJjZdvT11gc',
    appId: '1:1050523682496:android:6890993040d6def43f0f25',
    messagingSenderId: '1050523682496',
    projectId: 'netplixclone',
    storageBucket: 'netplixclone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsz_09Yit-vV0locIbW0hZq3rDhMhK8R8',
    appId: '1:1050523682496:ios:854a990e263e58a63f0f25',
    messagingSenderId: '1050523682496',
    projectId: 'netplixclone',
    storageBucket: 'netplixclone.appspot.com',
    iosClientId: '1050523682496-ga29opokee7vdhluoltgjefc0iu2biqk.apps.googleusercontent.com',
    iosBundleId: 'wspyo.netplixClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsz_09Yit-vV0locIbW0hZq3rDhMhK8R8',
    appId: '1:1050523682496:ios:854a990e263e58a63f0f25',
    messagingSenderId: '1050523682496',
    projectId: 'netplixclone',
    storageBucket: 'netplixclone.appspot.com',
    iosClientId: '1050523682496-ga29opokee7vdhluoltgjefc0iu2biqk.apps.googleusercontent.com',
    iosBundleId: 'wspyo.netplixClone',
  );
}
